---
title: "Text to SQL - Questions generation for the Statbot-Challenge"
output: html_notebook
---
https://towardsdatascience.com/text-to-sql-learning-to-query-tables-with-natural-language-7d714e60a70d

```{r setup}
library(tidyverse)
```


# 1. 

Read in a dataset with indicator metadata and short descriptions which can be used to generate questions.

```{r}
indicators <-
  read_csv("input_data/EN_INDICATORS.csv") %>%
  left_join(read_csv("input_data/indicators_desc.csv"),
            by=c("INDICATOR_ID"="indicator_id"))
```
# Combine Datasets

Combine the indicator dataset with the actual data.

```{r}
gp_data <- read_csv("input_data/EN_INDICATOR_VALUES.csv") %>% 
           left_join(indicators, by=c("INDICATOR_ID"="INDICATOR_ID")) %>% 
           rename(INDICATOR_NAME=NAME) %>% 
           left_join(read_csv("input_data/EN_T_SPATIALUNIT.csv"), by=c("SPATIALUNIT_ID"="SPATIALUNIT_ID")) %>%rename(UNIT_NAME=NAME) 
```

## 1. Value for a given Municipality / Indicator

Questions : what to do with the year? integrate explicitly in the question or just take max as standard?
```{r}

spatial_units <- read_csv("input_data/EN_T_SPATIALUNIT.csv") %>% 
                  select(SPATIALUNIT_ID,rand_mun_name=NAME)

filtered_indicators <- gp_data %>% 
  filter(TYPE_ID==1) %>% 
  group_by(INDICATOR_ID, INDICATOR_NAME, short_desc, questiontype) %>% 
  summarize(rand_val=sample(VALUE,1), 
            rand_year=sample(YEAR,1),
            rand_mun=sample(SPATIALUNIT_ID,1)) %>% 
                        filter(questiontype<=2) %>% 
  left_join(spatial_units, by=c("rand_mun"="SPATIALUNIT_ID"))

indicator <- filtered_indicators$short_desc

indicator_name <- filtered_indicators$INDICATOR_NAME

random_value <- filtered_indicators$rand_val

indicator_id <- filtered_indicators$INDICATOR_ID

indicator_year <- filtered_indicators$rand_year


municipality_id <- filtered_indicators$rand_mun

municipality <- filtered_indicators$rand_mun_name

questions_and_queries <- tibble(
                          questions = c("how high is the {indicator} in {municipality}?", 
                                        
                                       "which municipality has the highest {indicator}?",
                                       
                                       "Which municipality has the minimum {indicator}?",
                                       
                                        "what are the highest, lowest and average {indicator}?",
                                       
                                        "How many municipalities have a {indicator} higher than {random_value}?",
                                       
                                        "How high is the total {indicator} in the Canton Zurich?",
                                       
                                        "Which Region had the lowest {indicator} in the year {indicator_year}?"
                                       ),
                         
                           queries=c("select iv.value from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where i.name like '{indicator_name}' and s.name like '{municipality}'", 
                                     
                                      "select s.name from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where i.name like '{indicator_name}'",
                                     
                                      "select s.name from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where i.name like '{indicator_name}'",
                                     
                                      "select max(iv.value), min(iv.value), avg(iv.value) from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      where i.name like '{indicator_name}'",
                                     
                                      "select iv.year, count(*) from
                                      indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where iv.VALUE > {random_value} and s.type_id = 1 and i.name like '{indicator_name}' group by iv.year",
                                     
                                      "select iv.value from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where s.type_id=8 and i.name like '{indicator_name}'",
                                     
                                      "select min(iv.value), s.name from indicator_values2 iv
                                      join indicators i on iv.indicator_id = i.indicator_id
                                      join spatialunit s on iv.spatialunit_id = s.spatialunit_id
                                      where s.type_id=4 and iv.year={indicator_year} and i.name like '{indicator_name}'"
                                      )

)



dataframe <- tibble(
              question=purrr::map(questions_and_queries$questions, 
                                   ~glue::glue(.x)) %>% unlist(),
              sql=purrr::map(questions_and_queries$queries, 
                                    ~glue::glue(.x))%>% unlist()
              )

# save questions and queries
write.csv(dataframe,"questions_queries.csv")

# save table
write.csv(gp_data %>% head(10), "gp_data.csv")

```

```{r}

combinations <- tibble(
  indicator_
  indicator_id
  municipality
  year
  municipality_id
)







filtered_indicators$INDICATOR_ID

# sentences
string = purrr::map2_chr(1:length(filtered_indicators), question_list
         ~glue::glue()

# SQL
questions=
  tibble(sentence=purrr::map_chr(1:length(ind_com_list),
         ~glue::glue("how high is the {ind_com_list[[.x]][1]} in {ind_com_list[[.x]][2]}")),
         
         
          statement=purrr::map_chr(1:length(ind_com_list),~glue::glue("
SELECT VALUE FROM gp_data where INDICATOR_ID =  {ind_com_list[[.x]][1]} and UNIT_NAME = {ind_com_list[[.x]][2]}")))

#einbauen - filter auf indikator

questions %>% 
  mutate(sql=paste("SELECT", column , "from table", "where", where_column, where_operators, where_value))

```


question tokens
```{r}
how high is the 
which municipality has the highest 
what are the highest, lowest and average 



which are the runif() comunes with the highest 
What is the average , minimum , and maximum 
Show municipalities with a ,  , over x and more than , , 
Show names for all municipalities except for those having a x 
Find the weight of the youngest dog



questions <- c("how high is the {indicator} in {municipality}", 
               "which municipality has the highest {indicator}",
"what are the highest, lowest and average {indicator},
find the {indicator} of the municipality with the lowest {}")

```



